### ISSUE TITLE
Release `@nucypher/taco`

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/taco-web#308]
A checklist for the initial release of the new SDK version

- [x] Release `@nucypher/taco:0.1.0-rc.*`
  - Relesed `@nucypher/taco:0.1.0-rc.*` and `@nucypher/shared:0.1.0-rc.*`
- [x] Deprecate external TACo demos - #336
  - Archive repos, add StackBlitz links to READMEs in `./demos`, link `./demos` to Gitbook docs 
  - https://github.com/nucypher/nucypher-ts-demo-tdec
  - https://github.com/nucypher/tdec-nft-example
  - https://github.com/nucypher/tdec-sandbox
- [x] #300
- [x] #307
- [x] How do we fix git tags? I.e. avoiding duplicates with legacy `nucypher-ts` tags, tagging for different packages, etc. - Decided to keep them as they are for the legacy reasons
- [x] Update `README.md` - #336
- [x] Update `demos/README.md` and `demos/**/README.md` where appropriate - #336
- [x] Merge `alpha` and `beta` branches into `main`
- [x] Deploy `demos` on Netlify (`taco-demo` has disabled builds on Netlify)
- [x] #317

**Comment by piotr-roslaniec** [comment]
Closed by https://github.com/nucypher/taco-web/pull/461
